channels:
  - defaults
  - conda-forge
  - bioconda
  - main
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - biopython=1.86=py312h4c3975b_1
  - blas=1.0=openblas
  - blast=2.5.0=hc0b0e79_3
  - boost=1.82.0=py312h06a4308_2
  - bottle=0.13.2=py312h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hd44998d_0
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2026.01.04=py312h06a4308_0
  - cffi=2.0.0=py312h4eded50_1
  - charset-normalizer=3.4.4=py312h06a4308_0
  - colorama=0.4.6=py312h06a4308_0
  - curl=7.88.1=hdbd6064_2
  - entrez-direct=24.0=he881be0_0
  - ete4=4.3.0=py312h4c3975b_1
  - exceptiongroup=1.3.0=py312h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - fasttree=2.2.0=h7b50bb2_1
  - gettext=0.21.0=hedfda30_2
  - icu=73.1=h6a678d5_0
  - idna=3.11=py312h06a4308_0
  - iniconfig=2.3.0=py312h06a4308_0
  - jansson=2.14=h5eee18b_1
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.44=h153f514_2
  - libboost=1.82.0=h109eef0_2
  - libcurl=7.88.1=h251f7ec_2
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.18=h75a1612_0
  - libidn2=2.3.8=hf80d704_0
  - libnghttp2=1.67.1=h697f920_0
  - libnsl=2.0.0=h5eee18b_0
  - libopenblas=0.3.31=hf7dbefb_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - mcl=14.137=pl5262h779adbc_6
  - miniprot=0.18=h577a1d6_0
  - ncurses=6.5=h7934f7d_0
  - networkx=3.6.1=py312h06a4308_0
  - numpy=2.4.2=py312h35d6838_0
  - numpy-base=2.4.2=py312h4bc27c9_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py312h06a4308_1
  - pandas=3.0.1=py312h8ecdadd_0
  - pcre=8.45=h295c915_0
  - pcre2=10.46=hf426167_0
  - perl=5.26.2=h14c3975_0
  - perl-archive-tar=2.32=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-xsloader=0.24=pl526_0
  - pip=26.0.1=pyhc872135_0
  - pluggy=1.5.0=py312h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - py-boost=1.82.0=py312h6db74b5_2
  - pygments=2.19.2=py312h06a4308_0
  - pysocks=1.7.1=py312h06a4308_1
  - pytest=9.0.2=pyhcf101f3_0
  - python=3.12.12=hd17a9e1_1
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python_abi=3.12=3_cp312
  - quicktree=2.5=h7b50bb2_9
  - readline=8.3=hc2a1206_0
  - requests=2.32.5=py312h06a4308_1
  - scipy=1.17.0=py312h35deafb_0
  - setuptools=80.10.2=py312h06a4308_0
  - six=1.17.0=py312h06a4308_0
  - sonlib=2.0.dev88=py312he57d009_1
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.4.0=py312h06a4308_0
  - tqdm=4.67.3=pyh8f84b5b_0
  - trimal=1.5.1=h9948957_0
  - typing-extensions=4.15.0=py312h06a4308_0
  - typing_extensions=4.15.0=py312h06a4308_0
  - tzdata=2025c=he532380_0
  - urllib3=2.6.3=py312h06a4308_0
  - wget=1.25.0=he4200e1_2
  - wheel=0.46.3=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - addict==2.4.0
      - blessed==1.30.0
      - boto3==1.42.55
      - boto3-stubs==1.42.55
      - botocore==1.42.55
      - botocore-stubs==1.42.41
      - brotli==1.2.0
      - coloredlogs==15.0.1
      - configargparse==1.7.1
      - cryptography==46.0.5
      - dill==0.3.9
      - ec2-metadata==2.17.0
      - enlighten==1.14.1
      - humanfriendly==10.0
      - jinja2==3.1.6
      - jmespath==1.1.0
      - markupsafe==3.0.3
      - moto==5.1.21
      - mypy-boto3-autoscaling==1.42.33
      - mypy-boto3-ec2==1.42.51
      - mypy-boto3-iam==1.42.4
      - mypy-boto3-s3==1.42.37
      - mypy-boto3-sdb==1.42.3
      - mypy-boto3-sts==1.42.3
      - prefixed==0.9.0
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - pycparser==3.0
      - pypubsub==4.0.7
      - pyyaml==6.0.3
      - responses==0.26.0
      - ruamel-yaml==0.19.1
      - s3transfer==0.16.0
      - toil==9.1.2
      - types-awscrt==0.31.2
      - types-s3transfer==0.16.0
      - wcwidth==0.6.0
      - werkzeug==3.1.6
      - xmltodict==1.0.4
